### PR TITLE
Add windows download links to nightlies page

### PR DESCRIPTION
**Pull request by chadyj**
Adds Windows link and icon to nightlies page.

screen shot 2018-10-08 at 12 03 32 pm

### CODE REVIEW

**Comment by arnetheduck** [comment]
yay!

**Comment by jakubgs** [comment]
Okay, but what will be updating the links? We don't have an automatic Windows build yet, is it going to be manual for now?

**Comment by chadyj** [comment]
> Okay, but what will be updating the links? We don't have an automatic Windows build yet, is it going to be manual for now?

Ha this was just to get the cart in front of the horse and tease @PombeirP a little to spur on the windows dev.  Still has **WIP** title until his work is done.

**Comment by pedropombeiro** [comment]
We now have a working Jenkins build, so we can proceed with this. The open question is if we wait for the installer PR or we go ahead with the zip.

**Comment by chadyj** [comment]
> We now have a working Jenkins build, so we can proceed with this. The open question is if we wait for the installer PR or we go ahead with the zip.

Kudos @PombeirP!!!!

I'd say just go ahead considering there is an urgent need, and we can improve as we go.

**Comment by chadyj** [comment]
Closing since nightlies page moved to status.im

**Pull request closed without merging**
