### PR TITLE
nightly build warning message

### PR DESCRIPTION
**Pull request by chadyj**
Inform visitors of https://status-im.github.io/nightly/ the purpose and risks of nightlies.

screen shot 2018-10-19 at 8 47 00 am

<blockquote><div><strong><a href="https://status-im.github.io/nightly/">Status.im Nightly Builds</a></strong></div></blockquote>

### CODE REVIEW

**Comment by chadyj** [comment]
cc @sonyx6

**Comment by 0xc1c4da** [comment]
Maybe something along the lines of "we make no claims of security or integrity of funds in these builds"

**Comment by 0xc1c4da** [comment]
Maybe something along the lines of "we make no claims of security or integrity of funds in these builds"

**Review by jakubgs — APPROVED** [review]
Not pretty but does the job. We probably should have a web dev refresh the looks of this site.

**Comment by corpetty** [comment]
Can we get something that says something like "it is not advised to use the same recovery phrase as your tested release"?

**Review by corpetty — CHANGES_REQUESTED** [review]
Please add something like "it is not advised to use the same recovery phrase as your tested release software"

**Comment by chadyj** [comment]
@corpetty @jarradh incorporated suggestions. Ready to merge.

> Warning: Nightly builds are intended for development testing and may include bugs and other issues.
> 
> By downloading and installing these builds you assume the full responsibility for all risks concerning your data and funds. Status makes no claims of security or integrity of funds in these builds. Status advises the use of different recovery phrases in nightlies and stable builds.

**Comment by chadyj** [comment]
Haven't heard back from @corpetty or @jarradh but going to merge this since their suggestions were incorporated.

**Pull request merged**
